#!/bin/bash

# Run me like `sudo ./BuildImage git@gitlab.hallowelt.com:bluespicebuilds/build-pro.git pro 4.5.0 [optional:Docker-repoName]`
# Run me like `sudo ./BuildImage git@gitlab.hallowelt.com:bluespicebuilds/build-farm.git farm 4.3`
# You must have access to `gitlab.hallowelt.com:BlueSpiceBuilds/build-pro.git`

deploymentRepo="$1"
EDITION="$2"
PATCH="$3"
if [[ -z $4 ]]; then
	repoName="bluespice-"$EDITION
else
	repoName="$4"
fi

#patchVersion=${version%-*}
#minorVersion=${patchVersion%.*}
#majorVersion=${minorVersion%.*}

echo "Fetching codebase '${Version}-${Branch}' from ${deploymentRepo}'"
#rm -rf _codebase/bluespice
#git clone -b ${PATCH} --depth 1 ${deploymentRepo} _codebase/bluespice
#rm -rf _codebase/bluespice/.git/

    

dockerImageRegistry="docker.bluespice.com"
containerName=${EDITION}
containerIdBase="${dockerImageRegistry}/${repoName}/${containerName}"
	echo ""
	echo "Building '${containerIdBase}:${PATCH}'"
	docker build --no-cache -t ${containerIdBase}:latest .
	#docker push ${containerIdBase}:latest
	docker tag ${containerIdBase}:latest ${containerIdBase}:${PATCH}
	#docker push ${containerIdBase}:${PATCH}
	MINOR=${PATCH:0:3}
	docker tag ${containerIdBase}:latest ${containerIdBase}:${MINOR}
	#docker push ${containerIdBase}:${MINOR}
	MAJOR=${MINOR/0:1}
	docker tag ${containerIdBase}:latest ${containerIdBase}:${MAJOR}
	#docker push ${containerIdBase}:${MAJOR}



